version: '0.1'
services:
  bitcoin.mikedotexe.eth:
    image: 'bitcoin.mikedotexe.eth:0.1.0'
    build:
      context: ./build
      args:
        VERSION: "27.0"
    volumes:
      - 'bitcoin_data:/root/.bitcoin'
    ports:
      - '8333:8333'
      - '18332:18332'
      - '18333:18333'
      - '28332:28332'
      - '28333:28333'
    environment:
      - BTC_TXINDEX=1
      - BTC_PRUNE=1
      - BTC_TESTNET=1
    restart: always
volumes:
  bitcoin_data: {}
